sources:
  - name: cao
    base: http://crawl.akrasiac.org

    # Timezones are used if this server had games prior to Crawl using
    # only UTC in the logfile.
    timezones:
      D: '-0400'
      S: '-0500'

    utc-epoch: '200808070330+0000'

    # Regex -> location; player name is automatically appended.
    timestamps:
      - http://crawl.akrasiac.org/rawdata

    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/crawl.akrasiac.org/ttyrec
      - http://crawl.akrasiac.org/rawdata

  - name: cdo
    base: http://crawl.develz.org
    utc-epoch: '200808070330+0000'
    timezones:
      D: '+0200'
      S: '+0100'
    timestamps:
      - http://crawl.develz.org/morgues/trunk
      - http://crawl.develz.org/morgues/0.9
      - http://crawl.develz.org/morgues/$file_cv$/$name$
    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/crawl.develz.org/ttyrec
      - ttyrec: http://crawl.develz.org/ttyrecs
        listing: http://crawl.develz.org/cgi-bin/ttyrecs?$name$

  - name: cszo
    base: http://dobrazupa.org
    timestamps:
      - http://dobrazupa.org/morgue
    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/dobrazupa.org/ttyrec
      # - http://dobrazupa.org/ttyrec

  - name: cue
    base: http://underhound.eu:81/crawl
    timestamps:
      - http://underhound.eu:81/crawl/morgue
    ttyrecs:
      - http://underhound.eu:81/crawl/ttyrec

  - name: ckr
    base: http://kr.dobrazupa.org
    logfiles:
      - www/logfile
    milestones:
      - www/milestones
    morgues:
      - http://kr.dobrazupa.org/morgue/0.13
    ttyrecs:
      - http://kr.dobrazupa.org/ttyrecs
    timestamps:
      - http://kr.dobrazupa.org/morgue/0.13

  - name: cbro
    base: http://crawl.berotato.org/crawl
    timestamps:
      - http://crawl.berotato.org/crawl/morgue
    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/crawl.berotato.org/ttyrec
      - http://crawl.berotato.org/crawl/ttyrec

  - name: cbr2
    aliases:
      - cbro2
    base: https://cbro.berotato.org/
    morgues:
      - https://cbro.berotato.org/morgue
    ttyrecs:
      - https://cbro.berotato.org/ttyrec

  - name: cxc
    base: http://crawl.xtahua.com/crawl/meta
    logs:
      - git/{logfile,milestones}{,-sprint,-zotdef}*
    morgues:
      - http://crawl.xtahua.com/crawl/morgue
    timestamps:
      - http://crawl.xtahua.com/crawl/morgue
    ttyrecs:
      - http://crawl.xtahua.com/crawl/ttyrec

  - name: lld
    base: http://lazy-life.ddo.jp/mirror/meta
    logs:
      - '{trunk,0.14}/{logfile,milestones}{,-sprint,-zotdef}*'
      - '0.15/{logfile,milestones}*'
    timestamps:
      - [ 'lld.*-(0.\d+)', 'http://lazy-life.ddo.jp:8080/morgue-$1' ]
      - http://lazy-life.ddo.jp:8080/morgue
    ttyrecs:
      - http://lazy-life.ddo.jp/mirror/ttyrecs

  - name: cpo
    base: https://crawl.project357.org
    logs:
      - dcss-{milestones,logfiles}-{trunk,0.15}*
    timestamps:
      - https://crawl.project357.org/morgue
    ttyrecs:
      - https://crawl.project357.org/ttyrec

  - name: cjr
    base: https://crawl.jorgrun.rocks/meta
    logs:
      - '{0.17,0.18,git}/{milestones,logfile}{,-sprint,-zotdef}*'
    morgues:
      - https://crawl.jorgrun.rocks/morgue
    ttyrecs:
      - https://crawl.jorgrun.rocks/ttyrec

  - name: cko
    base: https://crawl.kelbi.org/crawl/meta
    logs:
      - '{0.21,0.22,git}/{milestones,logfile}{,-sprint,-zotdef}*'
    morgues:
      - https://crawl.kelbi.org/crawl/morgue
    ttyrecs:
      - https://crawl.kelbi.org/crawl/ttyrec

  - name: cwz
    base: https://webzook.net/soup
    logs:
      - '0.16/{logfile,milestones}-old'
      - '{0.13,0.14,0.15,0.16,0.17,0.18,0.19,0.20,0.21,0.22,0.23,0.24,trunk}/{logfile,milestones}*'
    morgues:
      - ['cwz.*/trunk', 'https://webzook.net/soup/morgue/trunk']
      - ['cwz.*/(\d+[.]\d+)', 'https://webzook.net/soup/morgue/$1']
    ttyrecs:
      - https://webzook.net/soup/ttyrecs
